[workspace]
resolver = "3"
members = [
    "deform_core",
    "deform_derive",
    "deform_quic",
    "deform_offline",
    "examples/*",
]
exclude = [

]

[workspace.dependencies]
wincode = { version = "0.5.4", default-features = false, features = ["alloc", "std", "derive"] }
solana-program-error = "3.0.1"
solana-address = { version = "2.6.0", features = ["wincode", "serde", "curve25519", "copy"] }
solana-client = "3.1.14"
solana-signature = "3.4.0"
serde = { version = "1.0.228", features = ["serde_derive"] }
tokio = { version = "1.48.0", default-features = false }
solana-sdk = { version = "4.0.1", default-features = false, features = ["full", "solana-signature"] } # "borsh"
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
webpki-roots = { version = "0.26" }
glam = { version = "0.30.7", default-features = false, features = ["bytemuck", "std", "serde"] } # debug-glam-assert
thiserror = "2.0.18"
better_tokio_select = "0.2"
bevy = "0.18.1"

# # Enable a small amount of optimization in the dev profile.
# [profile.dev]
# opt-level = 1

# # Enable a large amount of optimization in the dev profile for dependencies.
# [profile.dev.package."*"]
# opt-level = 3
