/* Backend-agnostic half of the DeFORM C bindings.
 *
 * Every fallible export returns a DeformByteBuffer holding one JSON object:
 *
 *     {"data": ...}      on success
 *     {"error": "..."}   on failure
 *
 * The buffer is owned by the caller and must be released with
 * deform_free_bytes. Buffers passed *in* are borrowed for the duration of the
 * call and are never freed by the library.
 *
 * Pubkeys cross the boundary as base58 strings. Lobbies cross as the raw
 * account data of the lobby PDA -- the same bytes getAccountInfo returns.
 *
 * The per-game symbols are generated by deform_ffi's export_* macros; see the
 * header next to the game's own crate (e.g. pong_ffi.h) for their signatures.
 */
#ifndef DEFORM_FFI_H
#define DEFORM_FFI_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Pointer + length. As an argument, memory you own; as a return value, memory
 * the library leaked for you. */
typedef struct {
  uint8_t *ptr;
  size_t size;
} DeformByteBuffer;

/* Releases a buffer returned by any DeFORM binding. Unlike free, the pointer
 * must not be null, and must not have been released already. Never call it on a
 * buffer you passed in. */
void deform_free_bytes(uint8_t *ptr, size_t size);

#ifdef __cplusplus
}
#endif

#endif /* DEFORM_FFI_H */
