[package]
name = "deform_program_anchor"
version = "0.1.0"
edition = "2021"

[dependencies]
deform_core = { path = "../deform_core", default-features = false }
deform_program = { path = "../deform_program" }
wincode = { workspace = true }
borsh = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
solana-address = { workspace = true, features = ["borsh"] }
solana-account-info = { workspace = true }
solana-cpi = { workspace = true }
solana-instruction = { workspace = true }
solana-program-error = { workspace = true }
solana-system-interface = { workspace = true }
