/* Pong's DeFORM C bindings, generated by deform_ffi's export_* macros.
 *
 * Usage:
 *   1. one of the pong_new_*_client calls returns {"data": <handle>}, an
 * integer that is the leaked DeformClient pointer;
 *   2. pass that handle to pong_read_state / pong_set_inputs / pong_shutdown;
 *   3. pong_free_client releases it (and cancels the backend if it is still
 * running).
 *
 * Every returned DeformByteBuffer must be released with deform_free_bytes.
 */
#ifndef PONG_FFI_H
#define PONG_FFI_H

#include "deform_ffi.h"

#ifdef __cplusplus
extern "C" {
#endif

/* --- backends: each returns {"data": <handle>} or {"error": "..."} --- */

/* Offline, every non-local player driven by the built-in bot.
 *
 * There is no lobby account offline, so the lobby is built from `players`: a
 * JSON array of base58 pubkeys whose FIRST entry is the creator. `player` picks
 * which of them this host drives, and must appear in the array. */
DeformByteBuffer pong_new_offline_client(
    DeformByteBuffer player,
    DeformByteBuffer players,
    uint64_t lobby_id,
    uint64_t visual_tick_micros);

/* Web2 QUIC server.
 *
 * `lobby_account` is the raw lobby PDA account data. Empty buffers take
 * defaults: `server_name` falls back to the host part of `server_addr`, `auth`
 * to a zero-byte wincode-encoded Auth, `fake_network` to the real network
 * (otherwise a FakeNetwork variant name such as "cellular" or "stress_test",
 * for latency testing). */
DeformByteBuffer pong_new_quic_client(
    DeformByteBuffer lobby_account,
    DeformByteBuffer player,
    DeformByteBuffer server_addr,
    DeformByteBuffer server_name,
    uint8_t skip_cert_verify,
    uint64_t visual_tick_micros,
    DeformByteBuffer auth,
    DeformByteBuffer fake_network);

/* Fully on-chain, over a MagicBlock ephemeral rollup.
 *
 * `lobby_account` is the raw lobby PDA account data and must be a FullyOnChain
 * lobby. `keypair` is a 32-byte ed25519 seed or the 64-byte layout of a Solana
 * keypair file. Empty `rpc_url`/`ws_url` and a zero `slot_time_micros` are
 * derived from the lobby's validator network. */
DeformByteBuffer pong_new_foc_client(
    DeformByteBuffer lobby_account,
    DeformByteBuffer keypair,
    DeformByteBuffer rpc_url,
    DeformByteBuffer ws_url,
    uint64_t visual_tick_micros,
    uint64_t slot_time_micros);

/* --- operations on a handle --- */

/* {"data": {"lobby": ..., "stats": {"ping_ms": ...}}}, or {"error": ...} if the
 * backend has failed. */
DeformByteBuffer pong_read_state(void *client);

/* Queues JSON-encoded PongInputs, e.g. {"direction":1}. Returns {"data": null}.
 */
DeformByteBuffer pong_set_inputs(void *client, DeformByteBuffer inputs_json);

/* Cancels the backend. The handle stays readable afterwards. */
DeformByteBuffer pong_shutdown(void *client);

/* Cancels the backend and drops the handle. Do not use the handle again. */
void pong_free_client(void *client);

#ifdef __cplusplus
}
#endif

#endif /* PONG_FFI_H */
