"""Export saved edits, GLB and headless collision/spawn data together.
Collision objects must remain unmodified cuboids; arbitrary translation/rotation/scale is supported.
"""
import bpy, json, math
from pathlib import Path
from mathutils import Matrix, Vector
ROOT=Path(__file__).resolve().parents[1]
scene=bpy.data.scenes['BOMB HOUSE'];bpy.context.window.scene=scene
bpy.context.view_layer.update()
# Blender Z-up -> glTF/Bevy Y-up.
basis=Matrix.Rotation(-math.pi/2,4,'X')
solids=[];spawns=[]
for ob in sorted(scene.objects,key=lambda o:o.name):
    if ob.get('airsoft_solid',False):
        if ob.type!='MESH' or len(ob.data.vertices)!=8 or len(ob.modifiers):
            raise RuntimeError(f'{ob.name}: collision requires an unmodified cuboid')
        transform=basis@ob.matrix_world
        center=transform@Vector(tuple((min(v[i] for v in ob.bound_box)+max(v[i] for v in ob.bound_box))/2 for i in range(3)))
        # Cube local axes stay Blender-local; full converted orientation maps them into Bevy.
        dims=[max(v[i] for v in ob.bound_box)-min(v[i] for v in ob.bound_box) for i in range(3)]
        scale=transform.to_scale();rot=transform.to_quaternion()
        solids.append({'name':ob.name,'center':list(center),'size':[dims[i]*abs(scale[i]) for i in range(3)],'rotation':[rot.x,rot.y,rot.z,rot.w]})
    if 'airsoft_spawn' in ob:
        spawns.append({'side':int(ob['airsoft_spawn']),'position':list(basis@ob.matrix_world.translation),'yaw':float(ob['yaw'])})
assert sorted(s['side'] for s in spawns)==[0,1], 'Exactly two spawn markers required'
spawns.sort(key=lambda s:s['side'])
(ROOT/'assets/levels').mkdir(parents=True,exist_ok=True)
bpy.ops.wm.save_as_mainfile(filepath=str(ROOT/'blender/bomb_house.blend'))
bpy.ops.export_scene.gltf(filepath=str(ROOT/'assets/levels/bomb_house.glb'),export_format='GLB',use_active_scene=True,export_cameras=False,export_lights=True,export_extras=True,export_tangents=True,export_apply=True,export_yup=True)
manifest={'solids':solids,'spawns':spawns}
(ROOT/'assets/levels/collision.json').write_text(json.dumps(manifest,indent=2)+'\n')
# Compile the exact exported data into every backend, including renderless servers.
def arr(values):return '['+', '.join(f'{v:.7f}' for v in values)+']'
lines=['#![allow(clippy::type_complexity, clippy::approx_constant, clippy::excessive_precision)]', '// Generated by blender/export_level.py. Edit the .blend, then re-export.',
       'pub const SOLIDS: &[([f32; 3], [f32; 3], [f32; 4])] = &[']
for s in solids:lines.append(f'    ({arr(s["center"])}, {arr(s["size"])}, {arr(s["rotation"])}),')
lines.extend(['];','pub const SPAWNS: &[([f32; 3], f32)] = &['])
for s in spawns:lines.append(f'    ({arr(s["position"])}, {s["yaw"]:.7f}),')
lines.append('];')
(ROOT/'src/arena_data.rs').write_text('\n'.join(lines)+'\n')
print(f'Exported GLB, {len(solids)} collision boxes, and {len(spawns)} spawns')

# On this Linux host, Blender's PulseAudio teardown can hang even with -noaudio.
# Synchronous save/export/manifest writes have all completed at this point.
if bpy.app.background:
    import sys, os
    sys.stdout.flush(); sys.stderr.flush()
    os._exit(0)
