[package]
name = "deform_ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[features]
default = []
offline = ["dep:deform_offline"]
quic = ["dep:deform_quic"]
foc = ["dep:deform_foc", "dep:solana-sdk"]

[dependencies]
deform_core = { workspace = true }
deform_offline = { workspace = true, optional = true }
deform_quic = { workspace = true, optional = true }
deform_foc = { workspace = true, optional = true }
solana-address = { workspace = true, features = ["decode"] }
solana-sdk = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio-util = { workspace = true }
wincode = { workspace = true }
paste = "1.0.15"
