services:
  surfpool:
    # image: surfpool/surfpool
    # local image built with `docker buildx build --platform linux/amd64 -t surfpool/surfpool:programsubscribe-local --load .` on the surfpool repo
    image: surfpool/surfpool:programsubscribe-local
    container_name: surfpool-instance
    ports:
    - "8899:8899"
    - "8900:8900"
    # - "18488:18488"
    volumes:
      - ../../../../../surfpool/:/workspace
      - ../../../../../anchor_program/target:/artifacts:ro
      - ../../../../../anchor_program/PRIVATE_DO_NOT_PUBLISH_THIS/admin.json:/root/.config/solana/id.json:ro
    command: start --no-tui
    restart: unless-stopped

  pong_server:
    image: pong-server:latest
    container_name: pong-server
    ports:
      - "4433:4433"
    volumes:
      - ../../../../../anchor_program/PRIVATE_DO_NOT_PUBLISH_THIS/admin.json:/app/admin.json:ro
    environment:
      - RUST_LOG=info
      - KEYPAIR_PATH=admin.json
    restart: unless-stopped
