[package]
name = "soccer"
version = "0.1.0"
edition = "2024"

[lib]

[[bin]]
name = "soccer"
required-features = ["bin"]

[features]
default = ["client", "server", "anchor", "foc-getslot", "20hz"]
bin = ["dep:clap", "deform_core/client", "dep:deform_offline", "dep:anyhow", "dep:solana-sdk", "dep:solana-client", "dep:solana-rpc-client", "dep:serde_json", "dep:deform_quic", "dep:tokio", "dep:tokio-util", "dep:tracing", "dep:tracing-subscriber", "dep:magicblock-magic-program-api"]
server = ["bin"]
client = ["bin", "dep:bevy", "dep:bevy_egui", "dep:bevy-egui-notify", "bevy/dynamic_linking", "dep:egui-probe", "deform_core/egui-probe"]
anchor = ["dep:anchor-lang", "solana-address/borsh", "deform_core/anchor"]
tracy = ["dep:tracy-client", "deform_quic/tracy", "deform_core/tracy", "deform_foc/tracy"]

foc = ["dep:deform_foc", "client"]
foc-getslot = ["foc", "deform_foc/rtt-getslot"]
foc-ping = ["foc", "deform_foc/rtt-ping"]
foc-inputs = ["foc", "deform_foc/rtt-inputs"]

60hz = []
20hz = []

[dependencies]
anchor-lang = { workspace = true, optional = true }
deform_core = { path = "../../deform_core" }
deform_offline = { path = "../../deform_offline", optional = true }
glam = { workspace = true }
serde = { workspace = true }
wincode = { workspace = true }
bevy = { workspace = true, optional = true }
bevy_egui = { workspace = true, optional = true }
bevy-egui-notify = { workspace = true, optional = true }
solana-address = { workspace = true, features = ["decode"] }
solana-instruction = { workspace = true }
solana-sdk = { workspace = true, optional = true }
solana-client = { workspace = true, optional = true }
solana-rpc-client = { workspace = true, optional = true }
anyhow = { version = "1.0.102", optional = true }
clap = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
deform_quic = { path = "../../deform_quic", optional = true }
deform_foc = { path = "../../deform_foc", optional = true, default-features = false }
tokio = { workspace = true, optional = true, features = ["rt-multi-thread", "macros"] }
tokio-util = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
tracy-client = { workspace = true, optional = true, default-features = true }
borsh = { workspace = true }
egui-probe = { workspace = true, optional = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
fastrand = { workspace = true }
thiserror = { workspace = true }
solana-account-info = { workspace = true }
solana-cpi = { workspace = true }
solana-program-error = { workspace = true }
solana-system-interface = { workspace = true }
ephemeral-rollups-sdk = { workspace = true }
magicblock-magic-program-api = { version = "0.10.1", default-features = false, optional = true }
