[package]
name = "deform_core"
version = "0.1.0"
edition = "2021"     # for solana compat

[lib]
crate-type = ["rlib"]

[dependencies]
anchor-lang = { workspace = true, optional = true }
deform_derive = { path = "../deform_derive" }
tokio = { workspace = true, features = ["sync"], optional = true }
serde = { workspace = true }
solana-program-error = { workspace = true }
wincode = { workspace = true }
glam = { workspace = true }
thiserror = { workspace = true }
solana-address = { workspace = true }
solana-instruction = { workspace = true }
tracy-client = { workspace = true, optional = true }

[features]
default = ["client"]
client = ["dep:tokio"]
anchor = ["solana-address/borsh", "dep:anchor-lang"]
tracy = ["dep:tracy-client"]
