[package]
name = "deform_core"
version = "0.1.0"
edition = "2021"     # for solana compat

[lib]
crate-type = ["rlib"]

[dependencies]
anchor-lang = { workspace = true, optional = true }
egui-probe = { workspace = true, optional = true }
deform_derive = { workspace = true }
tokio = { workspace = true, features = ["sync"], optional = true }
tokio-util = { workspace = true, optional = true }
serde = { workspace = true }
solana-program-error = { workspace = true }
wincode = { workspace = true }
glam = { workspace = true }
thiserror = { workspace = true }
solana-address = { workspace = true }
solana-instruction = { workspace = true }
deform_metrics = { workspace = true, optional = true }
strum = { workspace = true }
strum_macros = { workspace = true }

[features]
default = ["client"]
client = ["dep:tokio", "dep:tokio-util"]
anchor = ["solana-address/borsh", "dep:anchor-lang"]
metrics = ["dep:deform_metrics"]
egui-probe = ["dep:egui-probe"]
