[workspace]
resolver = "3"
members = [
    "deform_core",
    "deform_derive",
    "deform_quic",
    "deform_foc",
    "deform_offline",
    "examples/*",
]
exclude = [

]

[workspace.dependencies]
anyhow = "1.0.102"
wincode = { version = "0.5.5", default-features = false, features = ["alloc", "std", "derive"] }
borsh = { version = "1.6.1", features = ["derive"] }
num-derive = "0.4.2"
num-traits = "0.2.19"
# 0.11 tracks egui 0.34, matching bevy_egui 0.40
egui-probe = { version = "0.11", features = ["derive"] }
solana-account-info = "3.1.1"
solana-cpi = "3.1.0"
solana-instruction = "3.4.0"
solana-system-interface = "3.2.0"
solana-program-error = "3.0.1"
anchor-lang = { version = "1.0.2", default-features = false }
# borsh = { version = "1.6.1", default-features = false, features = ["derive", "std"] }
solana-address = { version = "2.6.0", features = ["wincode", "serde", "curve25519", "copy"] }
solana-client = "4.1.0-beta.3"
solana-signature = "3.4.0"
serde = { version = "1.0.228", features = ["serde_derive"] }
tokio = { version = "1.48.0", default-features = false }
tokio-util = "0.7.18"
solana-sdk = { version = "4.0.1", default-features = false, features = ["full", "solana-signature"] } # "borsh"
solana-rpc-client = "4.1.0-rc.1"
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
webpki-roots = { version = "0.26" }
thiserror = "2.0.18"
better_tokio_select = "0.2"
rustls-pemfile = "2.2.0"
rcgen = "0.14.8"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
clap = { version = "4.6.1", features = ["derive", "env"] }
serde_json = "1.0.150"
tracy-client = { version = "0.18", default-features = false }
strum = "0.28.0"
strum_macros = "0.28"
ephemeral-rollups-sdk = { version = "0.15.5" }

# deps shared between examples
bevy = "0.19.0"
# bevy_math = "0.19.0"
glam = { version = "0.32.1", default-features = false, features = ["bytemuck", "std", "serde"] } # debug-glam-assert # WARN: this needs to match bevy_math. I can't depend on bevy_math as bevy is locked to rustc 1.95, and solana is way behind
bevy_egui = "0.40.0"
bevy-egui-notify = { git = "https://github.com/IVSOP/bevy-egui-notify", rev = "f8e111d312a4c465a00ff2b86d6bc8be244ffcc2" }

# # Enable a small amount of optimization in the dev profile.
# [profile.dev]
# opt-level = 1

# # Enable a large amount of optimization in the dev profile for dependencies.
# [profile.dev.package."*"]
# opt-level = 3

[patch.crates-io]
wincode = { git = "https://github.com/anza-xyz/wincode", rev = "ce424cbcd1c3cca34ad16b8d462feb444fcbf172" }

