[workspace]
resolver = "3"
members = [
    "deform_core",
    "deform_derive",
    "deform_program",
    "deform_program_anchor",
    "deform_quic",
    "deform_offline",
    "examples/*",
]
exclude = [

]

[workspace.dependencies]
wincode = { version = "0.5.5", default-features = false, features = ["alloc", "std", "derive"] }
borsh = { version = "1.6.1", features = ["derive"] }
num-derive = "0.4.2"
num-traits = "0.2.19"
solana-account-info = "3.1.1"
solana-cpi = "3.1.0"
solana-instruction = "3.4.0"
solana-system-interface = "3.2.0"
solana-program-error = "3.0.1"
anchor-lang = { version = "1.0.2", default-features = false }
# borsh = { version = "1.6.1", default-features = false, features = ["derive", "std"] }
solana-address = { version = "2.6.0", features = ["wincode", "serde", "curve25519", "copy"] }
solana-client = "4.1.0-beta.3"
solana-signature = "3.4.0"
serde = { version = "1.0.228", features = ["serde_derive"] }
tokio = { version = "1.48.0", default-features = false }
solana-sdk = { version = "4.0.1", default-features = false, features = ["full", "solana-signature"] } # "borsh"
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
webpki-roots = { version = "0.26" }
glam = { version = "0.30.7", default-features = false, features = ["bytemuck", "std", "serde"] } # debug-glam-assert
thiserror = "2.0.18"
better_tokio_select = "0.2"

# deps shared between examples
bevy = "0.18.1"
bevy_egui = "0.39.1"

# # Enable a small amount of optimization in the dev profile.
# [profile.dev]
# opt-level = 1

# # Enable a large amount of optimization in the dev profile for dependencies.
# [profile.dev.package."*"]
# opt-level = 3
